name: Terraform-Apply-Infra-Release

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
      AWS_REGION: us-east-1
      TF_INPUT: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      # Simple + reliable: plan again on main for this commit, then apply that plan
      - name: Terraform Plan (main)
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -no-color -input=false -auto-approve tfplan
